# /backend/exporter.py
"""
MechaStream — ZIP exporter for build_app() output.
Produces a ready-to-run Next.js project in memory (no temp files).
"""

import zipfile
from io import BytesIO
from typing import Any, Dict


def _route_to_filename(route: str) -> str:
    """Map route to page filename without extension. '/' -> 'index', '/dashboard' -> 'dashboard'."""
    path = route.strip("/").replace("/", "-")
    return path if path else "index"


def _safe_title(build_result: Dict) -> str:
    """App title for folder and filename; safe for filesystem."""
    title = (build_result.get("title") or "my-app").strip()
    return "".join(c if c.isalnum() or c in " -_" else "" for c in title).strip() or "my-app"


def build_zip(build_result: Dict[str, Any]) -> BytesIO:
    """
    Build a downloadable zip from build_app() output.
    Returns BytesIO ready for Flask send_file. UTF-8, no temp files.
    """
    title = _safe_title(build_result)
    root = f"{title}"
    pages = build_result.get("pages") or {}
    theme = build_result.get("theme") or {}

    buf = BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:

        def add(path: str, content: str) -> None:
            zf.writestr(f"{root}/{path}", content.encode("utf-8"))

        # ─── Pages ───
        for route, data in pages.items():
            name = data.get("name", route)
            code = data.get("code", "")
            fname = _route_to_filename(route) + ".tsx"
            add(f"pages/{fname}", code)

        # ─── Reserved empty components dir ───
        add("components/.gitkeep", "# Reserved for V2\n")

        # ─── package.json ───
        add(
            "package.json",
            """{
  "name": "%s",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^14.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/node": "^20.0.0",
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "tailwindcss": "^3.4.0",
    "postcss": "^8.4.0",
    "autoprefixer": "^10.4.0"
  }
}
"""
            % title.replace(" ", "-").lower(),
        )

        # ─── tailwind.config.js ───
        add(
            "tailwind.config.js",
            """/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}"
  ],
  darkMode: "class",
  theme: { extend: {} },
  plugins: []
};
""",
        )

        # ─── tsconfig.json ───
        add(
            "tsconfig.json",
            """{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
""",
        )

        # ─── next.config.js ───
        add(
            "next.config.js",
            """/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
module.exports = nextConfig;
""",
        )

        # ─── README.md ───
        pages_list = "\n".join(
            f"- **{data.get('name', route)}** — `{route}`"
            for route, data in pages.items()
        )
        add(
            "README.md",
            f"""# {build_result.get('title', title)}

## Install & run

```bash
npm install
npm run dev
```

Then open [http://localhost:3000](http://localhost:3000).

## Pages

{pages_list if pages_list else "- (no pages)"}

---

Generated by MechaStream.
""",
        )

    buf.seek(0)
    return buf
